### ISSUE TITLE
 No module named 'DatExtractor'

### ISSUE THREAD

**Issue by httpanand** [subbu-art/DatExtractor#1]
**I installed it with pip and this comes**

**Comment by subbu-art** [comment]
Hi Anand,

Can you please share the screenshot. I have tried and I am able to install it.

![image](https://user-images.githubusercontent.com/56343858/126664715-e3de34c9-0829-4eca-a549-78f2e54c4d20.png)

**Comment by httpanand** [comment]
![image](https://user-images.githubusercontent.com/87514488/126732623-b2b285ee-63e9-4197-8c28-aa1e61982f43.png)

**Comment by subbu-art** [comment]
Cheers!, 
Glad that you were able to install it.
